### PR TITLE
Update for MR-Weather App

### PR DESCRIPTION
**Pull request by uturuncoglu**
This PR aims to update the application for UFS MR-Weather 1.1 release. The External.cfg contains following items;

- UFS MR-Weather Model: https://github.com/ufs-community/ufs-weather-model/commit/2c0b85669001c960e112413fdffe262c3ab873aa
- CIME: https://github.com/ESMCI/cime/commit/e0dcc59022a2dda74fcd5098b7bb8a6b0d96d2ee
- EMC_Post: https://github.com/NOAA-EMC/EMC_post/commit/bc6074f08d9b380bd9638ac269bf33c6ec52a641
- UFSATM CIME Interface: https://github.com/ESCOMP/FV3GFS_interface/commit/69b96bea23214146fa80d24852ae7364c2ab3022
- NEMS CIME Interface: https://github.com/ESCOMP/NEMS_interface/commit/3c36830475c1cfb9f1616678ecfa961329f3f608

### CODE REVIEW

**Comment by uturuncoglu** [comment]
@ligiabernardet @rsdunlapiv @climbfuji @arunchawla-NOAA Please make comment in this PR if you found any issue about the testing of the app. You could find more information about running full test suite in following link
https://github.com/ufs-community/ufs-mrweather-app/issues/184#issuecomment-689037713

**Comment by ligiabernardet** [comment]
Question about the UFS WM. The latest hash for release/public-v1 is 2c0b856. Should we use this one?
@climbfuji Pls advise on the contents of externals.cfg.

**Review by climbfuji — COMMENTED** [review]
Please use hash 2c0b85669001c960e112413fdffe262c3ab873aa for the model for the time being. We are still waiting for some documentation updates before we can create tag ufs-v1.1.0.

I see that the nems_interface has been tagged as ufs-v1.1.0 already?

**Comment by ligiabernardet** [comment]
Yes, NEMS was tagged last week.

**Comment by uturuncoglu** [comment]
Okay. I am updating the model hash.

**Comment by uturuncoglu** [comment]
I also updated PR comment and include the items in the External.cfg

**Review by climbfuji — APPROVED** [review]

**Comment by ligiabernardet** [comment]
Seems like there are conflicts in Externals.cfg that need to be resolved.
Are we waiting on the development to make the App regression tests run on Orion before the merge?

**Comment by uturuncoglu** [comment]
@ligiabernardet Let me know if you want me to solve the conflict.

**Comment by climbfuji** [comment]
> @ligiabernardet Let me know if you want me to solve the conflict.

Yes, we need to resolve those so that we can merge. Thank you ...

**Comment by ligiabernardet** [comment]
@uturuncoglu Pls resolve the conflict and let us know if we should go ahead with the merge or wait for the development that allows running RTs on Orion.

**Comment by uturuncoglu** [comment]
@ligiabernardet i need to install NCEPLIBS to test on Orion. If you want to wait for it it could take little bit time. BTW, the command line tool does not allow me to resolve the conflict and gives following error `fatal: release/public-v1 - not something we can merge` but I could do via web interface and then merge. We just need to pick the entries from ufs-release-v1.1. I am not sure why we have conflict in here.

**Comment by ligiabernardet** [comment]
@climbfuji Can you resolve the conflict? Then we can merge and proceed with testing outside of Orion.

**Comment by climbfuji** [comment]
@uturuncoglu I resolved the conflicts, can you please check if this is still what you want before I merge it?

**Comment by uturuncoglu** [comment]
@climbfuji Yes, it looks fine. I think you could merge it. Thanks

**Pull request merged**
